name: tpa
main: kr.skymin.tpa.Loader
api-version: 1.20
version: 1.0.0
author: skymin

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - org.jetbrains.kotlin:kotlin-reflect:1.9.0
  - io.github.monun:kommand-core:3.1.7